### ISSUE TITLE
False positive - storage-asset.msi.com

### ISSUE THREAD

**Issue by sefinek24** [alsyundawy/TrustPositif#1]
Broken website: https://pl.msi.com/Laptop/Alpha-17-C7VX/Specification
Blocklist: https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/gambling_indonesia.txt

Result:
![image](https://github.com/user-attachments/assets/8e7c8f23-b2a2-4cf1-a73c-2d12a9c611c1)

Expected:
![image](https://github.com/user-attachments/assets/f60ff84f-74e9-4b13-9a49-b2c7dead9a4e)

**Comment by alsyundawy** [comment]
yes it indonesia goverment fault, just whitelist 

wait, i will remove , thx @sefinek24
