### ISSUE TITLE
Splitting gambling_indonesia.txt into several files

### ISSUE THREAD

**Issue by sefinek** [alsyundawy/TrustPositif#2]
Hi, would it be possible to split `gambling_indonesia.txt` into several files? It's too large.
![{B975B996-F4BB-4AEF-89B5-9FC58C33AEEB}](https://github.com/user-attachments/assets/bc0bfc43-24a8-45f3-9cdf-d88ffde0588c)

**Comment by alsyundawy** [comment]
noted
